# Generated by Django 3.1.2 on 2020-11-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201127_1037'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='staffprofile',
            managers=[
            ],
        ),
    ]
