# Generated by Django 3.1.2 on 2020-11-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201127_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='user',
        ),
    ]
