# Generated by Django 3.1.2 on 2021-01-25 13:59

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageNodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.IntegerField()),
                ('instance', models.DateTimeField(auto_now_add=True)),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
            ],
            options={
                'ordering': ['amount'],
            },
        ),
    ]
