# Generated by Django 3.1.2 on 2020-11-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageNodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('placename', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
