# Generated by Django 3.1.2 on 2020-11-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagenodes',
            name='lat',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garbagenodes',
            name='lon',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garbagenodes',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
