# Generated by Django 3.1.2 on 2020-11-25 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_auto_20201125_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbagenodes',
            name='time',
        ),
    ]
