# Generated by Django 3.1.2 on 2020-11-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_remove_garbagenodes_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagenodes',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
